name: mseml2
channels:
  - defaults
dependencies:
  - jupyter==1.0.0
  - matplotlib==2.2.3
  - numpy==1.14.5
  - scikit-learn==0.19.1
  - scipy==1.1.0
  - tensorboard==1.10.0
  - tensorflow==1.10.0
  - python==3.6.6
  - pip==10.0.1
  - pip:
    - autograd==1.2
